new README

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,26 +12,23 @@ where '<option>' is one of the following:
 -c | --check      include internal checking code (forced by '-g')
 -s | --symbols    include symbol table (forced by '-g' but useful without)
 -p | --pedantic   pedantic compilation ('-Werror -std=c99 --pedantic')
+-d | --diagnose   print options for diagnosis (with compiler pragma messages)
                  
---no-block        disable blocking literals (thus slower propagation)
---no-bump         disable variable bumping (during conflict analysis)
---no-compact      disable compact watch data structures (slower + more space)
---no-learn        disable clause learning (do not add learned clauses)
---no-focused      disable focused mode and always use stable mode instead
---no-minimize     disable clause minimization (of learned 1st UIP clause)
---no-reduce       disable clause reduction (keep learned clauses forever)
---no-restart      disable restarting (otherwise moving average based)
---no-sort         disable sorting of bumped literals in focused mode
---no-stable       disable stable mode and always use focused mode instead
---no-variadic     disable embedding literals as variadic array into clauses
---no-vmtf         disable VMTF and always use VSIDS instead
---no-vsids        disable VSIDS and always use VMTF instead
+EOF
 
--f...             passed to compiler directly (like '-fsanitize=address')
+# The main feature options are in the following generated file.
+
+. features/usage.sh
+
+cat <<EOF
+
+-f... | -static   passed to compiler directly (like '-fsanitize=address')
 EOF
 }
 
 ############################################################################
+
+# Terminal colors for fancy output.
 
 if [ -t 1 ]
 then
@@ -54,25 +51,14 @@ die () {
 # Basic options.
 
 debug=no
+diagnose=no
 check=no
 symbols=no
 pedantic=no
 
 # Options to disable features (see also 'OPTIONS.md').
 
-block=yes
-bump=yes
-compact=yes
-focused=yes
-learn=yes
-minimize=yes
-reduce=yes
-restart=yes
-sort=yes
-stable=yes
-variadic=yes
-vmtf=yes
-vsids=yes
+. features/init.sh
 
 # Additional options such as '-f...'.
 
@@ -80,96 +66,48 @@ options=""
 
 ############################################################################
 
+. features/parse.sh
+
+config="$0"
+
 while [ $# -gt 0 ]
 do
-  case $1 in
+  case "$1" in
 
     --default) ;;
 
     -h|--help) usage; exit 0;;
 
     -g|--debug) debug=yes;;
-
     -c|--check) check=yes;;
     -s|--symbols) symbols=yes;;
     -p|--pedantic) pedantic=yes;;
+    -d|--diagnose) diagnose=yes;;
 
-    --no-block) block=no;;
-    --no-bump) bump=no;;
-    --no-compact) compact=no;;
-    --no-focused) focused=no;;
-    --no-learn) learn=no;;
-    --no-minimize) minimize=no;;
-    --no-reduce) reduce=no;;
-    --no-restart) restart=no;;
-    --no-sort) sort=no;;
-    --no-stable) stable=no;;
-    --no-variadic) variadic=no;;
-    --no-vmtf) vmtf=no;;
-    --no-vsids) vsids=no;;
+    -f*|-static) options="$options $1";;
 
-    -f*) options="$options $1";;
-
-    *) die "invalid option '$1' (try '-h')";;
+    *) parse "$1" || die "invalid option '$1' (try '-h')";;
   esac
+  config="$config $1"
   shift
 done
 
 ############################################################################
 
-# All checks of incompatible options.  Keep this in sync with the
-# 'incompatible' array in 'gencombi.c' (checked with 'make pairwise') as well
-# as with the corresponding checks in 'satch.c' (this needs to be checked
-# manually even though './gencombi -a -3 | ./checkconfig.sh' should catch
-# missing checks here).  See also 'OPTIONS.md' for more information.
+rm -f .config || exit 1
+echo "$config" > .config
+
+############################################################################
+
+. features/check.sh
+
+# All checks of incompatible options.
 
 [ $debug = yes -a $check = yes ] && \
   die "'--debug' implies '--check'"
 
 [ $debug = yes -a $symbols = yes ] && \
   die "'--debug' implies '--symbols'"
-
-[ $block = no -a $compact = no ] && \
-  die "'--no-block' implies '--no-compact'"
-
-if [ $bump = no ]
-then
-  [ $sort = no ] && \
-    die "'--no-bump' implies '--no-sort'"
-
-  [ $vmtf = no ] && \
-    die "'--no-bump' implies '--no-vmtf'"
-
-  [ $vsids = no ] && \
-    die "'--no-bump' implies '--no-vsids'"
-fi
-
-if [ $focused = no ]
-then
-  [ $stable = no ] && \
-    die "can not combine '--no-focused' and '--no-stable'"
-
-  [ $vmtf = no ] && \
-    die "'--no-focused' by default implies '--no-vmtf'"
-fi
-
-if [ $learn = no ]
-then
-  [ $reduce = no ] && \
-    die "'--no-learn' implies '--no-reduce'"
-
-  [ $minimize = no ] && \
-    die "'--no-learn' implies '--no-minimize'"
-fi
-
-[ $stable = no -a $vsids = no ] && \
-  die "'--no-stable' by default implies '--no-vsids'"
-
-[ $vmtf = no -a $sort = no ] && \
-  die "'--no-vmtf' implies '--no-sort'"
-
-[ $vmtf = no -a $vsids = no ] && \
-  die "can not combine '--no-vmtf' and '--no-vsids'"
 
 ############################################################################
 
@@ -191,19 +129,10 @@ fi
 
 [ $symbols = yes ] && CFLAGS="$CFLAGS -ggdb3"
 CFLAGS="$CFLAGS$options"
-[ $block = no ] && CFLAGS="$CFLAGS -DNBLOCK"
-[ $bump = no ] && CFLAGS="$CFLAGS -DNBUMP"
-[ $compact = no ] && CFLAGS="$CFLAGS -DNCOMPACT"
 [ $check = no ] && CFLAGS="$CFLAGS -DNDEBUG"
-[ $learn = no ] && CFLAGS="$CFLAGS -DNLEARN"
-[ $minimize = no ] && CFLAGS="$CFLAGS -DNMINIMIZE"
-[ $reduce = no ] && CFLAGS="$CFLAGS -DNREDUCE"
-[ $restart = no ] && CFLAGS="$CFLAGS -DNRESTART"
-[ $sort = no ] && CFLAGS="$CFLAGS -DNSORT"
-[ $stable = no ] && CFLAGS="$CFLAGS -DNSTABLE"
-[ $variadic = no ] && CFLAGS="$CFLAGS -DNVARIADIC"
-[ $vmtf = no ] && CFLAGS="$CFLAGS -DNVMTF"
-[ $vsids = no ] && CFLAGS="$CFLAGS -DNVSIDS"
+[ $diagnose = yes ] && CFLAGS="$CFLAGS -DIAGNOSE"
+
+. features/define.sh
 
 COMPILE="$CC $CFLAGS"
 echo "$COMPILE"
