release 0.4.7
- Almost complete colored solver messages (in 'report' etc.).
- Support for reading and encoding XNF (CNF with OR and XOR clauses).
- New makefile goals: test-two-ways, test-all-pairs, test-all-triples.
- Binary search in two-way combinatorial tester 'gencombi'.
- Code clean-up: sorted statistics fields, moved some internal code up.
- Using stable radix sort in 'reduce' allowed to remove clause ids.
- Radix sorting (to speed-up sorting of 'analyzed' stack).

diff --git a/features/configure b/features/configure
--- a/features/configure
+++ b/features/configure
@@ -4,9 +4,15 @@ usage () {
   exit 0
 }
 die () {
-  echo "configure: error: $*" 1>&2 
+  echo "${BOLD}configure: ${RED}error: ${NORMAL}$*" 1>&2
   exit 1
 }
+if [ -t 1 ]
+then
+  BOLD="\033[1m"
+  NORMAL="\033[0m"
+  RED="\033[1;31m"
+fi
 debug=no
 while [ $# -gt 0 ]
 do
